# Generated by Django 5.2.7 on 2025-11-28 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_produtos', to='agenda.barbershop')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='agenda.product')),
            ],
            options={
                'verbose_name': 'Venda de produto',
                'verbose_name_plural': 'Vendas de produtos',
            },
        ),
    ]
