# Generated by Django 5.2.7 on 2025-12-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_productsale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workdayconfig',
            options={'ordering': ['dia_semana', 'inicio']},
        ),
        migrations.AlterUniqueTogether(
            name='workdayconfig',
            unique_together=set(),
        ),
    ]
