# Generated by Django 6.0 on 2025-12-23 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_workdayconfig_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='tipo',
            field=models.CharField(choices=[('barbearia', 'Barbearia'), ('salao', 'Salão / Cabeleireiro'), ('manicure', 'Manicure'), ('sobrancelha', 'Sobrancelha'), ('maquiagem', 'Maquiagem'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
