# Generated by Django 6.0 on 2025-12-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_barbershop_tipo_alter_barbershop_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.service'),
        ),
    ]
