# Generated by Django 6.0 on 2025-12-28 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_appointment_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsale',
            options={},
        ),
        migrations.AddField(
            model_name='productsale',
            name='produto_nome',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agenda.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='valor_no_momento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço congelado na data em que o agendamento foi criado.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='agenda.product'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
