# Generated by Django 5.2.7 on 2026-02-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_productsale_options_productsale_produto_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='isento_pagamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='pago_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='plano',
            field=models.CharField(default='v1', max_length=20),
        ),
    ]
