# Generated by ChatGPT on 2026-02-06
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_plan", models.CharField(choices=[("V1", "V1 — Essencial"), ("V2", "V2 — Premium")], default="V1", max_length=2)),
                ("requested_plan", models.CharField(blank=True, choices=[("V1", "V1 — Essencial"), ("V2", "V2 — Premium")], max_length=2, null=True)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("is_exempt", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shop", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="subscription", to="agenda.barbershop")),
            ],
        ),
    ]
