# Generated by Django 5.2.7 on 2026-02-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_barbershop_ativo_barbershop_isento_pagamento_and_more'),
        ('agenda', '0100_plan_subscription'),
    ]

    operations = [
    ]
