# Generated by Django 5.2.7 on 2026-02-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0101_merge_20260207_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='isento_pagamento',
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='pago_ate',
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='plano',
        ),
    ]
