# Generated by ChatGPT patch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0102_remove_barbershop_ativo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("fixo", "Cliente fixo"), ("pausa", "Pausa")], default="fixo", max_length=10)),
                ("titulo", models.CharField(help_text="Ex.: João (pacote) / Almoço / Reunião", max_length=80)),
                ("dia_semana", models.IntegerField(choices=[(0, "Segunda"), (1, "Terça"), (2, "Quarta"), (3, "Quinta"), (4, "Sexta"), (5, "Sábado"), (6, "Domingo")], help_text="Dia da semana do bloqueio")),
                ("inicio", models.TimeField()),
                ("fim", models.TimeField()),
                ("duracao_minutos", models.PositiveIntegerField(blank=True, help_text="Opcional (para FIXO)", null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("barbearia", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recurring_blocks", to="agenda.barbershop")),
                ("servico", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="agenda.service")),
            ],
            options={
                "ordering": ("dia_semana", "inicio", "fim", "titulo"),
            },
        ),
    ]
